./DRU run2.mac output1.root
./DRU run2.mac output2.root
./DRU run2.mac output3.root
./DRU run2.mac output4.root
./DRU run2.mac output5.root
./DRU run2.mac output6.root
./DRU run2.mac output7.root
./DRU run2.mac output8.root
./DRU run2.mac output9.root
./DRU run2.mac output10.root
